$schema: http://json-schema.org/schema#
properties:
  cprcode:
    type: integer
  iprcode:
    type: integer
  psqty:
    type: integer
  pr_country_en:
    type: string
  online_category_l1_en:
    type: string
  online_category_l2_en:
    type: string
  online_category_l3_en:
    type: string
  hema_brand_en:
    type: string
  hema_sizedesc:
    type: string
  hema_name_en:
    type: string
  hema_name_th:
    type: string
  oprcode:
    type: integer
  ordertype:
    type: string
  pr_abb:
    type: string
  pr_active:
    type: boolean
  pr_cgcode:
    type: string
  pr_dpcode:
    type: string
  pr_engname:
    type: string
  pr_ggcode:
    type: string
  pr_market:
    type: string
  pr_name:
    type: string
  pr_sa_method:
    type: string
  pr_sucode1:
    type: string
  pr_suref3:
    type: string
  prtype:
    type: string
    enum:
    - I
    - C
  pstype:
    type: string
    enum:
    - '1'
    - '2'
    - '3'
  pr_country_th:
    type: string
  pr_keyword_th:
    type: string
  pr_keyword_en:
    type: string
  pr_filter_th:
    type: string
  pr_filter_en:
    type: string
  online_category_l1_th:
    type: string
  online_category_l2_th:
    type: string
  online_category_l3_th:
    type: string
  villa_category_l1_en:
    type: string
  villa_category_l2_en:
    type: string
  villa_category_l3_en:
    type: string
  villa_category_l4_en:
    type: string
  content_en:
    type: string
  content_th:
    type: string
  hema_brand_th:
    type: string
  pr_brand_en:
    type: string
  pr_brand_th:
    type: string
  pr_online_name_en:
    type: string
  pr_online_name_th:
    type: string
  pr_name_en:
    type: string
  pr_name_th:
    type: string
  sort_weight:
    type: number
  pr_barcode:
    type: string
  pr_barcode2:
    type: string
  master_online:
    type: boolean
  salemode_unit:
    type: string
  ba_nprice:
    type: number
  sort_villa_sku:
    type: number
  portion:
    type: string
  warehouse:
    type: integer
  consign_inv:
    type: integer
  enabled:
    type: boolean
  preorder_delivery_type:
    type: string
    enum:
    - fixed
    - relative
  preorder_fix_date:
    type: integer
  preorder_relative_day:
    type: integer
  product_detail_description:
    type: string
  meta_title:
    type: string
  meta_keyword:
    type: string
  meta_description:
    type: string
  height:
    type: number
  width:
    type: number
  depth:
    type: number
  weight:
    type: number
  priority_score:
    type: number
  avail_store:
    type: array
    items:
        type: string
  product_attribute_id:
    type: integer
  product_attribute:
    type: object
  related_products:
    type: array
    items:
        type: int      
required:
- salemode_unit
- ba_nprice
- cprcode
- hema_brand_en
- hema_name_en
- hema_sizedesc
- iprcode
- master_online
- online_category_l1_en
- online_category_l2_en
- pr_barcode
- pr_barcode2
- pr_online_name_en
- pr_suref3
- sort_villa_sku
- sort_weight
- villa_category_l1_en
- villa_category_l2_en
- villa_category_l3_en
- villa_category_l4_en
type: object
